---
charset: "UTF-8"
default_content_type: "text/plain"

template: template_toolkit

engines:
    template_toolkit:
        encoding:  'utf8'
        start_tag: '[%'
        stop_tag:  '%]'

auto_reload: 0

web_source: https://github.com/Perl/perl5
