#! /usr/bin/perl
use v5.10;
use warnings;
use strict;

use FindBin;
use lib "$FindBin::Bin/lib";
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../perl5/lib/perl5";
use lib "$FindBin::Bin/local/lib/perl5";

use Cwd qw/abs_path/;
use Dancer::Config;
use Dancer;
use Test::Smoke::Gateway::Dancer;

set views => path(abs_path(dirname(__FILE__)), 'templates');

dance();
