#! /usr/bin/perl
use 5.01000;
use warnings;
use strict;

use lib 'lib';
use lib '../lib';

use Cwd qw/abs_path/;
use Dancer::Config;
use Dancer;
use Test::Smoke::Gateway::Dancer;

set views => path(abs_path(dirname(__FILE__)), 'templates');
dance();
